return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "flake8",
      "pyright",
      "bash-debug-adapter",
      "ast-grep",
      "autopep8",
      "beautysh",
      "biome",
      "cfn-lint",
      "chrome-debug-adapter",
      "clang-format",
      "clangd",
      "codelldb",
      "cortex-debug",
      "cpplint",
      "cpptools",
      "csharp-language-server",
      "csharpier",
      "css-lsp",
      "css-variables-language-server",
      "cssmodules-language-server",
      "debugpy",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-language-server",
      "emmet-ls",
      "erb-lint",
      "eslint-lsp",
      "eslint_d",
      "firefox-debug-adapter",
      "fixjson",
      "glow",
      "go-debug-adapter",
      "graphql-language-service-cli",
      "hadolint",
      "html-lsp",
      "htmlbeautifier",
      "htmlhint",
      "hydra-lsp",
      "jq",
      "js-debug-adapter",
      "json-lsp",
      "jsonlint",
      "lua-language-server",
      "luacheck",
      "markmap-cli",
      "marksman",
      "markuplint",
      "netcoredbg",
      "nginx-language-server",
      "node-debug2-adapter",
      "nxls",
      "omnisharp",
      "omnisharp-mono",
      "prettier",
      -- "prettierd",
      "prisma-language-server",
      "prosemd-lsp",
      "pylint",
      "python-lsp-server",
      "ruff-lsp",
      "rust-analyzer",
      "rustywind",
      "selene",
      "shellcheck",
      "shfmt",
      "snyk",
      "some-sass-language-server",
      "sonarlint-language-server",
      "sql-formatter",
      "sqlfluff",
      "sqlfmt",
      "sqlls",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "trivy",
      "ts-standard",
      "typescript-language-server",
      "vim-language-server",
      "vtsls",
      "write-good",
      "yaml-language-server",
      "yamlfix",
      "yamlfmt",
      "yamllint",
      "zk",
      "markdown-oxide",
      -- "jdtls",
      "gopls",
      "bash-language-server",
      "java-debug-adapter",
    },
    cmd = {
      "Mason",
      "MasonInstall",
      "MasonInstallAll",
      "MasonUninstall",
      "MasonUninstallAll",
      "MasonLog",
    },
    ui = {
      icons = {
        package_installed = "",
        package_pending = "",
        package_uninstalled = "",
      },
    },
  },
}
